#!/usr/bin/env python3
"""
generate_project_table.py (optional)

Generates a Markdown project-showcase table by querying all public
repositories in the organization and selecting those tagged with a
designated GitHub topic (default: "robotronics-project").

This is intentionally a separate, optional script: wire it into the
same scheduled workflow, or a dedicated one, only once the club is
ready to tag repositories with the relevant topic. Running it before
any repository has the topic will simply produce an empty table with
a note rather than an error.

Environment variables:
    GITHUB_TOKEN     Required. GitHub API token.
    ORG_NAME          Required. Organization login.
    TOPIC             Optional. Topic used to discover project repos.
                       Defaults to "robotronics-project".
    OUTPUT_PATH       Optional. Where to write the Markdown fragment.
                       Defaults to assets/generated/project-table.md
"""

from __future__ import annotations

import os
import sys
import time
from typing import Optional

import requests

API_ROOT = "https://api.github.com"
PER_PAGE = 100
MAX_RETRIES = 3
RETRY_BACKOFF_SECONDS = 5

STATUS_BY_TOPIC = {
    "status-active": "Active",
    "status-development": "Development",
    "status-research": "Research",
    "status-archived": "Archived",
}


def _headers(token: str) -> dict:
    return {
        "Accept": "application/vnd.github+json",
        "Authorization": f"Bearer {token}",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _request(url: str, token: str, params: Optional[dict] = None) -> requests.Response:
    last_exception: Optional[Exception] = None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            resp = requests.get(url, headers=_headers(token), params=params, timeout=30)
        except requests.RequestException as exc:
            last_exception = exc
            time.sleep(RETRY_BACKOFF_SECONDS * attempt)
            continue
        if resp.status_code >= 500:
            time.sleep(RETRY_BACKOFF_SECONDS * attempt)
            continue
        return resp
    raise RuntimeError(f"Failed to reach {url} after {MAX_RETRIES} attempts: {last_exception}")


def paginated_get(url: str, token: str, params: Optional[dict] = None) -> list:
    items: list = []
    query = dict(params or {})
    query["per_page"] = PER_PAGE
    next_url: Optional[str] = url

    while next_url:
        resp = _request(next_url, token, params=query if next_url == url else None)
        if not resp.ok:
            raise RuntimeError(f"GitHub API error {resp.status_code} for {next_url}: {resp.text[:300]}")
        data = resp.json()
        items.extend(data if isinstance(data, list) else data.get("items", []))
        next_url = resp.links.get("next", {}).get("url")

    return items


def fetch_project_repos(org: str, token: str, topic: str) -> list:
    all_repos = paginated_get(
        f"{API_ROOT}/orgs/{org}/repos",
        token,
        params={"type": "public"},
    )
    matching = []
    for repo in all_repos:
        if repo.get("archived"):
            continue
        topics = repo.get("topics", [])
        if topic in topics:
            matching.append(repo)
    return matching


def infer_status(topics: list[str]) -> str:
    for topic, label in STATUS_BY_TOPIC.items():
        if topic in topics:
            return label
    return "Active"


def render_table(org: str, topic: str, repos: list) -> str:
    if not repos:
        return (
            f"<!-- Auto-generated by scripts/generate_project_table.py -->\n"
            f"No repositories are currently tagged with the `{topic}` topic.\n"
            f"Tag a repository with this topic on GitHub for it to appear here automatically.\n"
        )

    lines = [
        "<!-- Auto-generated by scripts/generate_project_table.py -->",
        "| Project | Description | Technologies | Status |",
        "|---|---|---|---|",
    ]
    for repo in sorted(repos, key=lambda r: r.get("name", "").lower()):
        name = repo.get("name", "")
        url = repo.get("html_url", "")
        description = (repo.get("description") or "").replace("|", "/").strip()
        language = repo.get("language") or "N/A"
        topics = repo.get("topics", [])
        status = infer_status(topics)
        lines.append(f"| [{name}]({url}) | {description} | {language} | {status} |")

    return "\n".join(lines) + "\n"


def main() -> int:
    token = os.environ.get("GITHUB_TOKEN")
    org = os.environ.get("ORG_NAME")
    topic = os.environ.get("TOPIC", "robotronics-project")
    output_path = os.environ.get("OUTPUT_PATH", "assets/generated/project-table.md")

    if not token:
        print("ERROR: GITHUB_TOKEN environment variable is not set.", file=sys.stderr)
        return 1
    if not org:
        print("ERROR: ORG_NAME environment variable is not set.", file=sys.stderr)
        return 1

    try:
        repos = fetch_project_repos(org, token, topic)
    except RuntimeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    table = render_table(org, topic, repos)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(table)

    print(f"Wrote project table ({len(repos)} project(s)) to {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
